export const hotelList = [
    { hotel: 'Hotels near me', path: '/near-me' },
    { hotel: 'Hotels in Manali', path: '/manali' },
    { hotel: 'Hotels in Nainital', path: '/nainital' },
    { hotel: 'Hotels in Mount Abu', path: '/mount-abu' },
    { hotel: 'Hotels in Agra', path: '/agra' },
    { hotel: 'Hotels in Haridwar', path: '/haridwar' },
    { hotel: 'Hotels in Gurgaon', path: '/gurgaon' },
    { hotel: 'Hotels in Coimbatore', path: '/coimbatore' },
    { hotel: 'Roomsstay Hotel UK', path: '/uk' },
    { hotel: 'Vacation Homes in Europe', path: '/europe' },
    { hotel: 'Hotels in Goa', path: '/goa' },
    { hotel: 'Hotels in Udaipur', path: '/udaipur' },
    { hotel: 'Hotels in Lonavala', path: '/lonavala' },
    { hotel: 'Hotels in Kodaikanal', path: '/kodaikanal' },
    { hotel: 'Hotels in Gangtok', path: '/gangtok' },
    { hotel: 'Hotels in Kolkata', path: '/kolkata' },
    { hotel: 'Hotels in Mandarmoni', path: '/mandarmoni' },
    { hotel: 'Hotels in Kasauli', path: '/kasauli' },
    { hotel: 'Roomsstay Hotel USA', path: '/usa' },
    { hotel: 'Homes in Scandinavia', path: '/scandinavia' },
    { hotel: 'Hotels in Puri', path: '/puri' },
    { hotel: 'Hotels in Mussoorie', path: '/mussoorie' },
    { hotel: 'Hotels in Munnar', path: '/munnar' },
    { hotel: 'Hotels in Hyderabad', path: '/hyderabad' },
    { hotel: 'Hotels in Coorg', path: '/coorg' },
    { hotel: 'Hotels in Ahmedabad', path: '/ahmedabad' },
    { hotel: 'Hotels in Daman', path: '/daman' },
    { hotel: 'Hotels in Dehradun', path: '/dehradun' },
    { hotel: 'Roomsstay Hotel Mexico', path: '/mexico' },
    { hotel: 'Homes in Southern Europe', path: '/southern-europe' },
    { hotel: 'Hotels in Shimla', path: '/shimla' },
    { hotel: 'Hotels in Mumbai', path: '/mumbai' },
    { hotel: 'Hotels in Darjeeling', path: '/darjeeling' },
    { hotel: 'Hotels in Shirdi', path: '/shirdi' },
    { hotel: 'Hotels in Dalhousie', path: '/dalhousie' },
    { hotel: 'Hotels in Varanasi', path: '/varanasi' },
    { hotel: 'Hotels in Madurai', path: '/madurai' },
];

export const amenitiesList = [
    { name: 'Pool', id: 'poolCheckbox' },
    { name: 'Fitness Center', id: 'fitnessCheckbox' },
    { name: 'Spa', id: 'spaCheckbox' },
    { name: 'Restaurant', id: 'restaurantCheckbox' },
    { name: 'Conference Room', id: 'conferenceRoomCheckbox' },
    { name: 'Wi-Fi Paid', id: 'wifiCheckbox' },
    { name: 'Parking', id: 'parkingCheckbox' },
    { name: 'Pet Friendly', id: 'petFriendlyCheckbox' },
    { name: 'Laundry Service', id: 'laundryCheckbox' },
    { name: 'Business Center', id: 'businessCenterCheckbox' },
    { name: 'Shuttle Service', id: 'shuttleCheckbox' },
    { name: '24-Hour Front Desk', id: 'frontDeskCheckbox' },
    { name: 'Gym', id: 'gymCheckbox' },
    { name: 'Lounge Area', id: 'loungeCheckbox' },
    { name: 'Free Wi-Fi', id: 'freeWifiCheckbox' },
    { name: 'TV', id: 'tvCheckbox' },
    { name: 'Air Conditioning', id: 'airConditioningCheckbox' },
    { name: 'Coffee Maker', id: 'coffeeMakerCheckbox' },
    { name: 'Balcony', id: 'balconyCheckbox' },
    { name: 'Jacuzzi', id: 'jacuzziCheckbox' },
    { name: 'Barbecue Area', id: 'barbecueCheckbox' },
    { name: 'Room Service', id: 'roomServiceCheckbox' },
    { name: 'Ensuite Bathroom', id: 'ensuiteBathroomCheckbox' },
    { name: 'Telephone', id: 'telephoneCheckbox' },
    { name: 'Daily Housekeeping', id: 'dailyHousekeepingCheckbox' },
    { name: 'Complimentary Toiletries', id: 'toiletriesCheckbox' },
    { name: 'Closet', id: 'closetCheckbox' },
    { name: 'Iron and Ironing Board', id: 'ironCheckbox' },
    { name: 'Hair Dryer', id: 'hairDryerCheckbox' },
    { name: 'Safe', id: 'safeCheckbox' },
    { name: 'Mini Fridge', id: 'miniFridgeCheckbox' },
    { name: 'Microwave', id: 'microwaveCheckbox' },
    { name: 'Desk', id: 'deskCheckbox' },
    { name: 'Wake-up Service', id: 'wakeUpServiceCheckbox' },
    { name: 'Heating', id: 'heatingCheckbox' },
    { name: 'Cable Channels', id: 'cableChannelsCheckbox' },
    { name: 'Non-Smoking Rooms', id: 'nonSmokingCheckbox' },
    { name: 'Soundproof Rooms', id: 'soundproofCheckbox' },
    { name: 'Family Rooms', id: 'familyRoomsCheckbox' },
    { name: 'Elevator', id: 'elevatorCheckbox' },
    { name: 'Wheelchair Accessible', id: 'wheelchairAccessibleCheckbox' },
    { name: 'Airport Shuttle', id: 'airportShuttleCheckbox' },
    { name: 'Concierge Service', id: 'conciergeCheckbox' },
    { name: 'Valet Parking', id: 'valetParkingCheckbox' },
    { name: 'Currency Exchange', id: 'currencyExchangeCheckbox' },
    { name: 'ATM on Site', id: 'atmCheckbox' },
    { name: 'Gift Shop', id: 'giftShopCheckbox' },
    { name: 'Express Check-in Check-out', id: 'expressCheckInCheckbox' },
    { name: 'Tour Desk', id: 'tourDeskCheckbox' },
    { name: 'Ticket Service', id: 'ticketServiceCheckbox' },
    { name: 'Luggage Storage', id: 'luggageStorageCheckbox' },
    { name: 'Library', id: 'libraryCheckbox' },
    { name: 'Sun Terrace', id: 'sunTerraceCheckbox' },
    { name: 'Garden', id: 'gardenCheckbox' },
    { name: 'Picnic Area', id: 'picnicAreaCheckbox' },
    { name: 'Outdoor Furniture', id: 'outdoorFurnitureCheckbox' },
    { name: 'Terrace', id: 'terraceCheckbox' },
    { name: 'BBQ Facilities', id: 'bbqFacilitiesCheckbox' },
    { name: 'Vending Machine Drinks', id: 'vendingMachineDrinksCheckbox' },
    { name: 'Vending Machine Snacks', id: 'vendingMachineSnacksCheckbox' },
    { name: 'Special Diet Menus on request', id: 'specialDietMenusCheckbox' },
    { name: 'Packed Lunches', id: 'packedLunchesCheckbox' },

    { name: 'Bar', id: 'barCheckbox' },
    { name: 'Wine Champagne', id: 'wineChampagneCheckbox' },
    { name: 'Bottle of Water', id: 'bottleOfWaterCheckbox' },
    { name: 'Chocolate Cookies', id: 'chocolateCookiesCheckbox' },
    { name: 'Kid-Friendly Buffet', id: 'kidFriendlyBuffetCheckbox' },
    { name: 'Kid Meals', id: 'kidMealsCheckbox' },
    { name: 'Breakfast in the Room', id: 'breakfastInRoomCheckbox' },
    { name: 'Restaurant Buffet', id: 'restaurantBuffetCheckbox' },
    { name: 'Snack Bar', id: 'snackBarCheckbox' },

    { name: 'Fruit', id: 'fruitCheckbox' },
    { name: 'Buffet Breakfast', id: 'buffetBreakfastCheckbox' },
    { name: 'Continental Breakfast', id: 'continentalBreakfastCheckbox' },
    { name: 'Gluten-Free Options', id: 'glutenFreeOptionsCheckbox' },
    { name: 'Vegetarian Options', id: 'vegetarianOptionsCheckbox' },
    { name: 'Vegan Options', id: 'veganOptionsCheckbox' },
    { name: 'Halal Options', id: 'halalOptionsCheckbox' },
    { name: 'Kosher Options', id: 'kosherOptionsCheckbox' },
    { name: 'Allergy-Free Room', id: 'allergyFreeRoomCheckbox' },
    { name: 'Designated Smoking Area', id: 'smokingAreaCheckbox' },
    { name: 'Non-Smoking Throughout', id: 'nonSmokingThroughoutCheckbox' },
    { name: 'Kitchen', id: 'kitchen' },
];

// Define filter options
import {
    Wine,
    Utensils,
    Phone,
    Coffee,
    DoorOpen,
    Bath,
    Tv,
    Wifi,
    Dumbbell,
    Bus,
    Waves,
    Sparkles,
    Presentation,
    ParkingCircle,
    Dog,
    Shirt,
    Briefcase,
    Armchair,
    Snowflake,
    Flame,
    ShowerHead,
    PhoneCall,
    SprayCan,
    Droplet,
    Luggage,
    Lock,
    Clock,
    Thermometer,
    Ban,
    Volume2,
    BedDouble,
    Accessibility,
    Plane,
    Users,
    Car,
    DollarSign,
    Gift,
    ClipboardCheck,
    MapPin,
    Ticket,
    BookOpen,
    Sun,
    Leaf,
    Trees,
    Building2,
    Martini,
    CandyCane,
    Apple,
    Sandwich,
    Cookie,
    Baby,
    Carrot,
    Landmark,
    Star,
    AlertCircle,
    Cigarette,
    Wind,
    Refrigerator,
    ArrowUpDown,
    Monitor,
    Microwave
} from 'lucide-react';

export const propertyTypes = [
    'Hotel',
    'Motel',
    'Hostel',
    'Guesthouse',
    'Bed and Breakfast',
    'Apartment',
    'Resort',
    'Villa',
    'Inn',
    'Chalet',
];

export const starRatings = ['1', '2', '3', '4', '5'];

const amenityIcons = {
    'Continental Breakfast': <Utensils className="w-4 h-4" />,
    'Room Service': <Phone className="w-4 h-4" />,
    'Coffee Maker': <Coffee className="w-4 h-4" />,
    'Balcony': <DoorOpen className="w-4 h-4" />,
    'Jacuzzi': <Bath className="w-4 h-4" />,
    'TV': <Tv className="w-4 h-4" />,
    'Free Wi-Fi': <Wifi className="w-4 h-4" />,
    'Gym': <Dumbbell className="w-4 h-4" />,
    '24-Hour Front Desk': <Bus className="w-4 h-4" />,
    'Shuttle Service': <Bus className="w-4 h-4" />,
    'Pool': <Waves className="w-4 h-4" />,
    'Fitness Center': <Dumbbell className="w-4 h-4" />,
    'Spa': <Sparkles className="w-4 h-4" />,
    'Restaurant': <Utensils className="w-4 h-4" />,
    'Conference Room': <Presentation className="w-4 h-4" />,
    'Wi-Fi(Paid)': <Wifi className="w-4 h-4" />,
    'Parking': <ParkingCircle className="w-4 h-4" />,
    'Pet Friendly': <Dog className="w-4 h-4" />,
    'Laundry Service': <Shirt className="w-4 h-4" />,
    'Business Center': <Briefcase className="w-4 h-4" />,
    'Lounge Area': <Armchair className="w-4 h-4" />,
    'Air Conditioning': <Snowflake className="w-4 h-4" />,
    'Barbecue Area': <Flame className="w-4 h-4" />,
    'Ensuite Bathroom': <ShowerHead className="w-4 h-4" />,
    Telephone: <PhoneCall className="w-4 h-4" />,
    'Daily Housekeeping': <SprayCan className="w-4 h-4" />,
    'Complimentary Toiletries': <Droplet className="w-4 h-4" />,
    Closet: <Luggage className="w-4 h-4" />,
    'Iron and Ironing Board': <Shirt className="w-4 h-4" />,
    'Hair Dryer': <Wind className="w-4 h-4" />,
    Safe: <Lock className="w-4 h-4" />,
    'Mini Fridge': <Refrigerator className="w-4 h-4" />,
    'Microwave': <Microwave className="w-4 h-4" />,
    'Desk': <Monitor className="w-4 h-4" />,
    'Wake-up Service': <Clock className="w-4 h-4" />,
    'Heating': <Thermometer className="w-4 h-4" />,
    'Cable Channels': <Tv className="w-4 h-4" />,
    'Non-Smoking Rooms': <Ban className="w-4 h-4" />,
    'Soundproof Rooms': <Volume2 className="w-4 h-4" />,
    'Family Rooms': <BedDouble className="w-4 h-4" />,
    'Elevator': <ArrowUpDown className="w-4 h-4" />,
    'Wheelchair Accessible': <Accessibility className="w-4 h-4" />,
    'Airport Shuttle': <Plane className="w-4 h-4" />,
    'Concierge Service': <Users className="w-4 h-4" />,
    'Valet Parking': <Car className="w-4 h-4" />,
    'Currency Exchange': <DollarSign className="w-4 h-4" />,
    'ATM on Site': <DollarSign className="w-4 h-4" />,
    'Gift Shop': <Gift className="w-4 h-4" />,
    'Express Check-in/Check-out': <ClipboardCheck className="w-4 h-4" />,
    'Tour Desk': <MapPin className="w-4 h-4" />,
    'Ticket Service': <Ticket className="w-4 h-4" />,
    'Luggage Storage': <Luggage className="w-4 h-4" />,
    'Library': <BookOpen className="w-4 h-4" />,
    'Sun Terrace': <Sun className="w-4 h-4" />,
    'Garden': <Leaf className="w-4 h-4" />,
    'Picnic Area': <Trees className="w-4 h-4" />,
    'Outdoor Furniture': <Armchair className="w-4 h-4" />,
    'Terrace': <Building2 className="w-4 h-4" />,
    'BBQ Facilities': <Flame className="w-4 h-4" />,
    'Vending Machine (Drinks)': <Martini className="w-4 h-4" />,
    'Vending Machine (Snacks)': <CandyCane className="w-4 h-4" />,
    'Special Diet Menus (on request)': <Apple className="w-4 h-4" />,
    'Packed Lunches': <Sandwich className="w-4 h-4" />,
    'Bar': <Martini className="w-4 h-4" />,
    'Wine/Champagne': <Wine className="w-4 h-4" />,
    'Bottle of Water': <Droplet className="w-4 h-4" />,
    'Chocolate/Cookies': <Cookie className="w-4 h-4" />,
    'Kid-Friendly Buffet': <Baby className="w-4 h-4" />,
    'Kid Meals': <Baby className="w-4 h-4" />,
    'Breakfast in the Room': <Utensils className="w-4 h-4" />,
    'Restaurant Buffet': <Utensils className="w-4 h-4" />,
    'Snack Bar': <Utensils className="w-4 h-4" />,
    'Fruit': <Apple className="w-4 h-4" />,
    'Buffet Breakfast': <Utensils className="w-4 h-4" />,
    'Gluten-Free Options': <Ban className="w-4 h-4" />,
    'Vegetarian Options': <Carrot className="w-4 h-4" />,
    'Vegan Options': <Leaf className="w-4 h-4" />,
    'Halal Options': <Landmark className="w-4 h-4" />,
    'Kosher Options': <Landmark className="w-4 h-4" />,
    'Allergy-Free Room': <AlertCircle className="w-4 h-4" />,
    'Designated Smoking Area': <Cigarette className="w-4 h-4" />,
    'Non-Smoking Throughout': <Ban className="w-4 h-4" />,
    'Kitchen': <Utensils className="w-4 h-4" />,
};
export default amenityIcons;

export const termsArray = [
    'Guests must present a valid ID upon check-in.',
    'Pets are not allowed on the premises.',
    'Cancellations must be made 24 hours in advance.',
    'Late check-out is subject to availability and may incur additional charges.',
    'Management reserves the right to refuse service.',
];

export const categories = [
    { name: 'Family-friendly' },
    { name: 'Nature' },
    { name: 'Romantic' },
    { name: 'Cultural' },
    { name: 'Holiday' },
    { name: 'General' },
];

export const bannerImage = [
    'https://images.unsplash.com/photo-1561501900-3701fa6a0864?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bHV4dXJ5JTIwaG90ZWx8ZW58MHx8MHx8fDA%3D',
    'https://kundutirthoovraman.com/wp-content/uploads/2019/03/europe_banner.jpg',
    'https://images.pexels.com/photos/2664046/pexels-photo-2664046.jpeg',
    'https://ic.c4assets.com/vps/grand-indian-hotel/f445ca4c-66d4-4884-ae39-7b8460e0172e.jpg',
];