export const hotelList = [
    { hotel: 'Hotels near me', path: '/near-me' },
    { hotel: 'Hotels in Manali', path: '/manali' },
    { hotel: 'Hotels in Nainital', path: '/nainital' },
    { hotel: 'Hotels in Mount Abu', path: '/mount-abu' },
    { hotel: 'Hotels in Agra', path: '/agra' },
    { hotel: 'Hotels in Haridwar', path: '/haridwar' },
    { hotel: 'Hotels in Gurgaon', path: '/gurgaon' },
    { hotel: 'Hotels in Coimbatore', path: '/coimbatore' },
    { hotel: 'Roomsstay Hotel UK', path: '/uk' },
    { hotel: 'Vacation Homes in Europe', path: '/europe' },
    { hotel: 'Hotels in Goa', path: '/goa' },
    { hotel: 'Hotels in Udaipur', path: '/udaipur' },
    { hotel: 'Hotels in Lonavala', path: '/lonavala' },
    { hotel: 'Hotels in Kodaikanal', path: '/kodaikanal' },
    { hotel: 'Hotels in Gangtok', path: '/gangtok' },
    { hotel: 'Hotels in Kolkata', path: '/kolkata' },
    { hotel: 'Hotels in Mandarmoni', path: '/mandarmoni' },
    { hotel: 'Hotels in Kasauli', path: '/kasauli' },
    { hotel: 'Roomsstay Hotel USA', path: '/usa' },
    { hotel: 'Homes in Scandinavia', path: '/scandinavia' },
    { hotel: 'Hotels in Puri', path: '/puri' },
    { hotel: 'Hotels in Mussoorie', path: '/mussoorie' },
    { hotel: 'Hotels in Munnar', path: '/munnar' },
    { hotel: 'Hotels in Hyderabad', path: '/hyderabad' },
    { hotel: 'Hotels in Coorg', path: '/coorg' },
    { hotel: 'Hotels in Ahmedabad', path: '/ahmedabad' },
    { hotel: 'Hotels in Daman', path: '/daman' },
    { hotel: 'Hotels in Dehradun', path: '/dehradun' },
    { hotel: 'Roomsstay Hotel Mexico', path: '/mexico' },
    { hotel: 'Homes in Southern Europe', path: '/southern-europe' },
    { hotel: 'Hotels in Shimla', path: '/shimla' },
    { hotel: 'Hotels in Mumbai', path: '/mumbai' },
    { hotel: 'Hotels in Darjeeling', path: '/darjeeling' },
    { hotel: 'Hotels in Shirdi', path: '/shirdi' },
    { hotel: 'Hotels in Dalhousie', path: '/dalhousie' },
    { hotel: 'Hotels in Varanasi', path: '/varanasi' },
    { hotel: 'Hotels in Madurai', path: '/madurai' },
];

export const amenitiesList = [
    { name: 'Pool', id: 'poolCheckbox' },
    { name: 'Fitness Center', id: 'fitnessCheckbox' },
    { name: 'Spa', id: 'spaCheckbox' },
    { name: 'Restaurant', id: 'restaurantCheckbox' },
    { name: 'Conference Room', id: 'conferenceRoomCheckbox' },
    { name: 'Wi-Fi Paid', id: 'wifiCheckbox' },
    { name: 'Parking', id: 'parkingCheckbox' },
    { name: 'Pet Friendly', id: 'petFriendlyCheckbox' },
    { name: 'Laundry Service', id: 'laundryCheckbox' },
    { name: 'Business Center', id: 'businessCenterCheckbox' },
    { name: 'Shuttle Service', id: 'shuttleCheckbox' },
    { name: '24-Hour Front Desk', id: 'frontDeskCheckbox' },
    { name: 'Gym', id: 'gymCheckbox' },
    { name: 'Lounge Area', id: 'loungeCheckbox' },
    { name: 'Free Wi-Fi', id: 'freeWifiCheckbox' },
    { name: 'TV', id: 'tvCheckbox' },
    { name: 'Air Conditioning', id: 'airConditioningCheckbox' },
    { name: 'Coffee Maker', id: 'coffeeMakerCheckbox' },
    { name: 'Balcony', id: 'balconyCheckbox' },
    { name: 'Jacuzzi', id: 'jacuzziCheckbox' },
    { name: 'Barbecue Area', id: 'barbecueCheckbox' },
    { name: 'Room Service', id: 'roomServiceCheckbox' },
    { name: 'Ensuite Bathroom', id: 'ensuiteBathroomCheckbox' },
    { name: 'Telephone', id: 'telephoneCheckbox' },
    { name: 'Daily Housekeeping', id: 'dailyHousekeepingCheckbox' },
    { name: 'Complimentary Toiletries', id: 'toiletriesCheckbox' },
    { name: 'Closet', id: 'closetCheckbox' },
    { name: 'Iron and Ironing Board', id: 'ironCheckbox' },
    { name: 'Hair Dryer', id: 'hairDryerCheckbox' },
    { name: 'Safe', id: 'safeCheckbox' },
    { name: 'Mini Fridge', id: 'miniFridgeCheckbox' },
    { name: 'Microwave', id: 'microwaveCheckbox' },
    { name: 'Desk', id: 'deskCheckbox' },
    { name: 'Wake-up Service', id: 'wakeUpServiceCheckbox' },
    { name: 'Heating', id: 'heatingCheckbox' },
    { name: 'Cable Channels', id: 'cableChannelsCheckbox' },
    { name: 'Non-Smoking Rooms', id: 'nonSmokingCheckbox' },
    { name: 'Soundproof Rooms', id: 'soundproofCheckbox' },
    { name: 'Family Rooms', id: 'familyRoomsCheckbox' },
    { name: 'Elevator', id: 'elevatorCheckbox' },
    { name: 'Wheelchair Accessible', id: 'wheelchairAccessibleCheckbox' },
    { name: 'Airport Shuttle', id: 'airportShuttleCheckbox' },
    { name: 'Concierge Service', id: 'conciergeCheckbox' },
    { name: 'Valet Parking', id: 'valetParkingCheckbox' },
    { name: 'Currency Exchange', id: 'currencyExchangeCheckbox' },
    { name: 'ATM on Site', id: 'atmCheckbox' },
    { name: 'Gift Shop', id: 'giftShopCheckbox' },
    { name: 'Express Check-in Check-out', id: 'expressCheckInCheckbox' },
    { name: 'Tour Desk', id: 'tourDeskCheckbox' },
    { name: 'Ticket Service', id: 'ticketServiceCheckbox' },
    { name: 'Luggage Storage', id: 'luggageStorageCheckbox' },
    { name: 'Library', id: 'libraryCheckbox' },
    { name: 'Sun Terrace', id: 'sunTerraceCheckbox' },
    { name: 'Garden', id: 'gardenCheckbox' },
    { name: 'Picnic Area', id: 'picnicAreaCheckbox' },
    { name: 'Outdoor Furniture', id: 'outdoorFurnitureCheckbox' },
    { name: 'Terrace', id: 'terraceCheckbox' },
    { name: 'BBQ Facilities', id: 'bbqFacilitiesCheckbox' },
    { name: 'Vending Machine Drinks', id: 'vendingMachineDrinksCheckbox' },
    { name: 'Vending Machine Snacks', id: 'vendingMachineSnacksCheckbox' },
    { name: 'Special Diet Menus on request', id: 'specialDietMenusCheckbox' },
    { name: 'Packed Lunches', id: 'packedLunchesCheckbox' },

    { name: 'Bar', id: 'barCheckbox' },
    { name: 'Wine Champagne', id: 'wineChampagneCheckbox' },
    { name: 'Bottle of Water', id: 'bottleOfWaterCheckbox' },
    { name: 'Chocolate Cookies', id: 'chocolateCookiesCheckbox' },
    { name: 'Kid-Friendly Buffet', id: 'kidFriendlyBuffetCheckbox' },
    { name: 'Kid Meals', id: 'kidMealsCheckbox' },
    { name: 'Breakfast in the Room', id: 'breakfastInRoomCheckbox' },
    { name: 'Restaurant Buffet', id: 'restaurantBuffetCheckbox' },
    { name: 'Snack Bar', id: 'snackBarCheckbox' },

    { name: 'Fruit', id: 'fruitCheckbox' },
    { name: 'Buffet Breakfast', id: 'buffetBreakfastCheckbox' },
    { name: 'Continental Breakfast', id: 'continentalBreakfastCheckbox' },
    { name: 'Gluten-Free Options', id: 'glutenFreeOptionsCheckbox' },
    { name: 'Vegetarian Options', id: 'vegetarianOptionsCheckbox' },
    { name: 'Vegan Options', id: 'veganOptionsCheckbox' },
    { name: 'Halal Options', id: 'halalOptionsCheckbox' },
    { name: 'Kosher Options', id: 'kosherOptionsCheckbox' },
    { name: 'Allergy-Free Room', id: 'allergyFreeRoomCheckbox' },
    { name: 'Designated Smoking Area', id: 'smokingAreaCheckbox' },
    { name: 'Non-Smoking Throughout', id: 'nonSmokingThroughoutCheckbox' },
    { name: 'Kitchen', id: 'kitchen' },
];

// Define filter options
import {
    FaWineGlass,
    FaUtensils,
    FaPhone,
    FaCoffee,
    FaDoorOpen,
    FaHotTub,
    FaTv,
    FaWifi,
    FaDumbbell,
    FaShuttleVan,
    FaSwimmingPool,
    FaSpa,
    FaChalkboardTeacher,
    FaParking,
    FaDog,
    FaTshirt,
    FaBriefcase,
    FaCouch,
    FaSnowflake,
    FaFireAlt,
    FaShower,
    FaPhoneAlt,
    FaBroom,
    FaSoap,
    FaSuitcase,
    FaLock,
    FaClock,
    FaThermometer,
    FaSmokingBan,
    FaVolumeMute,
    FaBed,
    FaWheelchair,
    FaPlaneDeparture,
    FaUserFriends,
    FaCar,
    FaMoneyBillAlt,
    FaGift,
    FaClipboardCheck,
    FaMapMarkedAlt,
    FaTicketAlt,
    FaBookOpen,
    FaSun,
    FaLeaf,
    FaTree,
    FaChair,
    FaCity,
    FaCocktail,
    FaCandyCane,
    FaAppleAlt,
    FaHamburger,
    FaCookieBite,
    FaChild,
    FaBan,
    FaCarrot,
    FaMosque,
    FaStarOfDavid,
    FaAllergies,
    FaSmoking,
} from 'react-icons/fa';
import { BiSolidDryer } from 'react-icons/bi';
import { LuRefrigerator } from 'react-icons/lu';
import { FaElevator } from 'react-icons/fa6';
import { GiDesk } from 'react-icons/gi';
import { MdMicrowave } from 'react-icons/md';



export const propertyTypes = [
    'Hotel',
    'Motel',
    'Hostel',
    'Guesthouse',
    'Bed and Breakfast',
    'Apartment',
    'Resort',
    'Villa',
    'Inn',
    'Chalet',
];

export const starRatings = ['1', '2', '3', '4', '5'];

const amenityIcons = {
    'Continental Breakfast': <FaUtensils />,
    'Room Service': <FaPhone />,
    'Coffee Maker': <FaCoffee />,
    'Balcony': <FaDoorOpen />,
    'Jacuzzi': <FaHotTub />,
    'TV': <FaTv />,
    'Free Wi-Fi': <FaWifi />,
    'Gym': <FaDumbbell />,
    '24-Hour Front Desk': <FaShuttleVan />,
    'Shuttle Service': <FaShuttleVan />,
    'Pool': <FaSwimmingPool />,
    'Fitness Center': <FaDumbbell />,
    'Spa': <FaSpa />,
    'Restaurant': <FaUtensils />,
    'Conference Room': <FaChalkboardTeacher />,
    'Wi-Fi(Paid)': <FaWifi />,
    'Parking': <FaParking />,
    'Pet Friendly': <FaDog />,
    'Laundry Service': <FaTshirt />,
    'Business Center': <FaBriefcase />,
    'Lounge Area': <FaCouch />,
    'Air Conditioning': <FaSnowflake />,
    'Barbecue Area': <FaFireAlt />,
    'Ensuite Bathroom': <FaShower />,
    Telephone: <FaPhoneAlt />,
    'Daily Housekeeping': <FaBroom />,
    'Complimentary Toiletries': <FaSoap />,
    Closet: <FaSuitcase />,
    'Iron and Ironing Board': <FaTshirt />,
    'Hair Dryer': <BiSolidDryer />,
    Safe: <FaLock />,
    'Mini Fridge': <LuRefrigerator />,
    'Microwave': <MdMicrowave />,
    'Desk': <GiDesk />,
    'Wake-up Service': <FaClock />,
    'Heating': <FaThermometer />,
    'Cable Channels': <FaTv />,
    'Non-Smoking Rooms': <FaSmokingBan />,
    'Soundproof Rooms': <FaVolumeMute />,
    'Family Rooms': <FaBed />,
    'Elevator': <FaElevator />,
    'Wheelchair Accessible': <FaWheelchair />,
    'Airport Shuttle': <FaPlaneDeparture />,
    'Concierge Service': <FaUserFriends />,
    'Valet Parking': <FaCar />,
    'Currency Exchange': <FaMoneyBillAlt />,
    'ATM on Site': <FaMoneyBillAlt />,
    'Gift Shop': <FaGift />,
    'Express Check-in/Check-out': <FaClipboardCheck />,
    'Tour Desk': <FaMapMarkedAlt />,
    'Ticket Service': <FaTicketAlt />,
    'Luggage Storage': <FaSuitcase />,
    'Library': <FaBookOpen />,
    'Sun Terrace': <FaSun />,
    'Garden': <FaLeaf />,
    'Picnic Area': <FaTree />,
    'Outdoor Furniture': <FaChair />,
    'Terrace': <FaCity />,
    'BBQ Facilities': <FaFireAlt />,
    'Vending Machine (Drinks)': <FaCocktail />,
    'Vending Machine (Snacks)': <FaCandyCane />,
    'Special Diet Menus (on request)': <FaAppleAlt />,
    'Packed Lunches': <FaHamburger />,
    'Bar': <FaCocktail />,
    'Wine/Champagne': <FaWineGlass />,
    'Bottle of Water': <FaCocktail />,
    'Chocolate/Cookies': <FaCookieBite />,
    'Kid-Friendly Buffet': <FaChild />,
    'Kid Meals': <FaChild />,
    'Breakfast in the Room': <FaUtensils />,
    'Restaurant Buffet': <FaUtensils />,
    'Snack Bar': <FaUtensils />,
    'Fruit': <FaAppleAlt />,
    'Buffet Breakfast': <FaUtensils />,
    'Gluten-Free Options': <FaBan />,
    'Vegetarian Options': <FaCarrot />,
    'Vegan Options': <FaLeaf />,
    'Halal Options': <FaMosque />,
    'Kosher Options': <FaStarOfDavid />,
    'Allergy-Free Room': <FaAllergies />,
    'Designated Smoking Area': <FaSmoking />,
    'Non-Smoking Throughout': <FaSmokingBan />,
    'Kitchen': <FaUtensils />,
};
export default amenityIcons;

export const termsArray = [
    'Guests must present a valid ID upon check-in.',
    'Pets are not allowed on the premises.',
    'Cancellations must be made 24 hours in advance.',
    'Late check-out is subject to availability and may incur additional charges.',
    'Management reserves the right to refuse service.',
];

export const categories = [
    { name: 'Family-friendly' },
    { name: 'Nature' },
    { name: 'Romantic' },
    { name: 'Cultural' },
    { name: 'Holiday' },
    { name: 'General' },
];

export const bannerImage = [
    'https://images.unsplash.com/photo-1561501900-3701fa6a0864?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bHV4dXJ5JTIwaG90ZWx8ZW58MHx8MHx8fDA%3D',
    'https://kundutirthoovraman.com/wp-content/uploads/2019/03/europe_banner.jpg',
    'https://images.pexels.com/photos/2664046/pexels-photo-2664046.jpeg',
    'https://ic.c4assets.com/vps/grand-indian-hotel/f445ca4c-66d4-4884-ae39-7b8460e0172e.jpg',
];
